
import dbConn.oraDBCredentials;
import java.awt.Color;
import java.awt.FontFormatException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import fontPackage.fontStyles;
import images.imageNames;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import colors.colors;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kevin
 */
public class congratsForm extends javax.swing.JFrame {
    public int account_id, difficulty;
    String subject;
    oraDBCredentials db = new oraDBCredentials();
    
    /**
     * Creates new form congratsForm
     * @throws java.awt.FontFormatException
     * @throws java.io.IOException
     */
    public congratsForm(String subj, int acc_id, int diff, int correct, int points) throws FontFormatException, FontFormatException, IOException{
        initComponents();
        this.getContentPane().setBackground(new Color(255,247,209));
        this.setLocationRelativeTo(null);
        setFonts();
        setImages();
        account_id = acc_id;
        difficulty = diff;
        subject = subj;
        showAdvanceBtn();
        lbl_pts.setText("Points: "+String.valueOf(points));
        lbl_total.setText(String.valueOf(correct)+"/15");
    }
    
    void showAdvanceBtn(){
        if(difficulty == 1){
            if(btn_playAdvance.isVisible()){
            }else{
                btn_playAdvance.setVisible(true);
            }
        }else{
            btn_playAdvance.setVisible(false);
        }
    }

    private congratsForm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    final void setFonts() throws FontFormatException, FontFormatException, IOException, IOException, IOException{
        lbl_congrats.setFont(fontStyles.setMaely(36));
        btn_playAgain.setFont(fontStyles.setOpenSans(18));
        btn_playAdvance.setFont(fontStyles.setOpenSans(18));
        btn_home.setFont(fontStyles.setOpenSans(18));
        lbl_pts.setFont(fontStyles.setMaely(16));
        lbl_total.setFont(fontStyles.setMaely(20));
    }
    
    final void setImages(){
        lbl_asteriskImg1.setIcon(imageNames.getImage(lbl_asteriskImg1.getWidth(),lbl_asteriskImg1.getHeight(),"*"));
        lbl_asteriskImg2.setIcon(imageNames.getImage(lbl_asteriskImg2.getWidth(),lbl_asteriskImg2.getHeight(),"*"));
        lbl_asteriskImg3.setIcon(imageNames.getImage(lbl_asteriskImg3.getWidth(),lbl_asteriskImg3.getHeight(),"*"));
        
        lbl_asteriskImg1.setText(null);
        lbl_asteriskImg2.setText(null);
        lbl_asteriskImg3.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbl_congrats = new javax.swing.JLabel();
        btn_playAgain = new javax.swing.JButton();
        btn_playAdvance = new javax.swing.JButton();
        btn_home = new javax.swing.JButton();
        lbl_asteriskImg3 = new javax.swing.JLabel();
        lbl_asteriskImg2 = new javax.swing.JLabel();
        lbl_asteriskImg1 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        lbl_pts = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(168, 135, 157));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(168, 135, 157));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(168, 135, 157));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(168, 135, 157));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        lbl_congrats.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_congrats.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_congrats.setText("Congratulations!");

        btn_playAgain.setBackground(new java.awt.Color(255, 212, 131));
        btn_playAgain.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_playAgain.setText("Play Again");
        btn_playAgain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_playAgainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_playAgainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_playAgainMouseExited(evt);
            }
        });

        btn_playAdvance.setBackground(new java.awt.Color(255, 212, 131));
        btn_playAdvance.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_playAdvance.setText("Play Advance Level");
        btn_playAdvance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_playAdvanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_playAdvanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_playAdvanceMouseExited(evt);
            }
        });

        btn_home.setBackground(new java.awt.Color(255, 212, 131));
        btn_home.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_home.setText("Back to Home");
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
        });

        lbl_asteriskImg3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_asteriskImg3.setText("Asterisk Img");

        lbl_asteriskImg2.setText("Asterisk Img");

        lbl_asteriskImg1.setText("Asterisk Img");

        lbl_total.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_total.setText("8/15");

        lbl_pts.setText("Points: 14");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_playAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_asteriskImg3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_playAdvance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_asteriskImg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_pts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lbl_asteriskImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_congrats)))
                        .addContainerGap(61, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_asteriskImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_congrats, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_asteriskImg3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_playAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_asteriskImg2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_playAdvance, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_pts, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_home, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(lbl_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(28, 28, 28))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
        try {
            // TODO add your handling code here:
            goHome();
        } catch (SQLException | FontFormatException | IOException ex) {
            Logger.getLogger(congratsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_homeMouseClicked

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        // TODO add your handling code here:
        btn_home.setForeground(colors.green);
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_playAdvanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_playAdvanceMouseEntered
        // TODO add your handling code here:
        btn_playAdvance.setForeground(colors.green);
    }//GEN-LAST:event_btn_playAdvanceMouseEntered

    private void btn_playAgainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_playAgainMouseEntered
        // TODO add your handling code here:
        btn_playAgain.setForeground(colors.green);
    }//GEN-LAST:event_btn_playAgainMouseEntered

    private void btn_playAgainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_playAgainMouseExited
        // TODO add your handling code here:
        btn_playAgain.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_playAgainMouseExited

    private void btn_playAdvanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_playAdvanceMouseExited
        // TODO add your handling code here:
        btn_playAdvance.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_playAdvanceMouseExited

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        // TODO add your handling code here:
        btn_home.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_homeMouseExited

    private void btn_playAgainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_playAgainMouseClicked
        try {
            // TODO add your handling code here:
            playAgain();
        } catch (FontFormatException | IOException | SQLException ex) {
            Logger.getLogger(congratsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_playAgainMouseClicked

    private void btn_playAdvanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_playAdvanceMouseClicked
        try {
            // TODO add your handling code here:
            playAdvance();
        } catch (FontFormatException | IOException | SQLException ex) {
            Logger.getLogger(congratsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_playAdvanceMouseClicked
    void playAdvance() throws FontFormatException, IOException, SQLException{
        this.dispose();
        questionForm qForm = new questionForm(subject, 2, account_id);
        qForm.setVisible(true);
    }
    
    void playAgain() throws FontFormatException, IOException, SQLException{
        this.dispose();
        questionForm qForm = new questionForm(subject, difficulty, account_id);
        qForm.setVisible(true);
    }
    
    void goHome() throws SQLException, FontFormatException, IOException{
        db.conn = DriverManager.getConnection(db.DB_URL, db.USER, db.PASS);
        String sql = String.format("SELECT USER_ID from LOGIN where account_id='%d'",account_id);
        PreparedStatement ps = db.conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        rs.next();
        String uID = rs.getString(1);
        
        sql = String.format("SELECT sum(total) "
                    + "FROM("
                        + "SELECT points as total, account_id "
                        + "FROM ENGLISH "
                        + "UNION ALL "
                        + "SELECT points, account_id "
                        + "FROM GEOGRAPHY "
                        + "UNION ALL "
                        + "SELECT points, account_id "
                        + "FROM MATH "
                        + "UNION ALL "
                        + "SELECT points, account_id "
                        + "FROM MUSICARTS "
                        + "UNION ALL "
                        + "SELECT points, account_id "
                        + "FROM SCIENCE "
                    + ") T "
                        + "WHERE T.account_id = '%d' "
                        + "GROUP BY T.account_id",account_id);
        ps = db.conn.prepareStatement(sql);
        rs = ps.executeQuery();
        rs.next();
        int pts = rs.getInt(1);
        
        this.dispose();
        dashboardForm dash = new dashboardForm();
        dash.setPoints(pts);
        dash.setName(uID);
        dash.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(congratsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(congratsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(congratsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(congratsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
                new congratsForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_playAdvance;
    private javax.swing.JButton btn_playAgain;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl_asteriskImg1;
    private javax.swing.JLabel lbl_asteriskImg2;
    private javax.swing.JLabel lbl_asteriskImg3;
    private javax.swing.JLabel lbl_congrats;
    private javax.swing.JLabel lbl_pts;
    private javax.swing.JLabel lbl_total;
    // End of variables declaration//GEN-END:variables
}
