/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Graphics;
import java.awt.font.TextAttribute;
import java.io.IOException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import fontPackage.fontStyles;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.prompt.PromptSupport;
import roundedFields.roundedPassField;
import roundedFields.roundedTextField;
import dbConn.oraDBCredentials;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author kevin
 */
public class loginForm extends javax.swing.JFrame {
    Graphics graphics;
    oraDBCredentials db = new oraDBCredentials();
    
    
    /**
     * Creates new form loginForm
     * @throws java.io.IOException
     * @throws java.awt.FontFormatException
     */
    public loginForm() throws IOException, FontFormatException {
        initComponents();
        this.getContentPane().setBackground(new Color(122,114,189));
        this.setTitle("Login Form");
        this.setLocationRelativeTo(null);
        setFont();
        PromptSupport.setPrompt("Enter your Name", txt_User);
        PromptSupport.setPrompt("Enter your Password", txt_Pass);
        addEnter();
    }

    private void addEnter(){
        txt_User.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if(e.getKeyCode() == KeyEvent.VK_ENTER){
                    try {
                        loginCheck();
                    } catch (SQLException ex) {
                        Logger.getLogger(loginForm.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (FontFormatException ex) {
                        Logger.getLogger(loginForm.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(loginForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
        txt_Pass.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if(e.getKeyCode() == KeyEvent.VK_ENTER){
                    try {
                        loginCheck();
                    } catch (SQLException ex) {
                        Logger.getLogger(loginForm.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (FontFormatException ex) {
                        Logger.getLogger(loginForm.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(loginForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
    }
    
    final void setFont() throws FontFormatException, IOException{
        txt_User.setFont(fontStyles.setMaely(24));
        txt_Pass.setFont(fontStyles.setMaely(24));
        btn_Enter.setFont(fontStyles.setMaely(24));
        
        Font font = lbl_signUp.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        lbl_signUp.setFont(font.deriveFont(attributes));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_User = new roundedTextField(15);//javax.swing.JTextField();
        btn_Enter = new javax.swing.JButton();
        txt_Pass = new roundedPassField(15);//javax.swing.JPasswordField();
        panel1 = new java.awt.Panel();
        panel4 = new java.awt.Panel();
        panel5 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        panel3 = new java.awt.Panel();
        panel6 = new java.awt.Panel();
        lbl_signUp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));

        txt_User.setBackground(new java.awt.Color(255, 196, 28));
        txt_User.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_User.setForeground(new java.awt.Color(255, 255, 255));
        txt_User.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_User.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btn_Enter.setBackground(new java.awt.Color(253, 253, 150));
        btn_Enter.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_Enter.setText("ENTER");
        btn_Enter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EnterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_EnterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EnterMouseExited(evt);
            }
        });

        txt_Pass.setBackground(new java.awt.Color(255, 196, 28));
        txt_Pass.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_Pass.setForeground(new java.awt.Color(255, 255, 255));
        txt_Pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Pass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        panel1.setBackground(new java.awt.Color(245, 126, 154));
        panel1.setEnabled(false);
        panel1.setPreferredSize(new java.awt.Dimension(10, 170));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel4.setBackground(new java.awt.Color(245, 126, 154));
        panel4.setEnabled(false);
        panel4.setPreferredSize(new java.awt.Dimension(10, 170));
        panel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel5.setBackground(new java.awt.Color(245, 126, 154));
        panel5.setEnabled(false);
        panel5.setPreferredSize(new java.awt.Dimension(10, 170));
        panel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel4.add(panel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panel1.add(panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panel2.setBackground(new java.awt.Color(245, 126, 154));
        panel2.setEnabled(false);
        panel2.setPreferredSize(new java.awt.Dimension(150, 10));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel3.setBackground(new java.awt.Color(245, 126, 154));
        panel3.setEnabled(false);
        panel3.setPreferredSize(new java.awt.Dimension(150, 10));
        panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel6.setBackground(new java.awt.Color(245, 126, 154));
        panel6.setEnabled(false);
        panel6.setPreferredSize(new java.awt.Dimension(10, 170));
        panel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_signUp.setForeground(new java.awt.Color(255, 255, 255));
        lbl_signUp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_signUp.setText("Sign Up");
        lbl_signUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_signUpMouseClicked(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("New Player? ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_User, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(103, 103, 103))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_Enter, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(lbl_signUp, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(193, 193, 193)))
                                .addComponent(panel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(txt_User, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(txt_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btn_Enter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_signUp)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 170, Short.MAX_VALUE)
                        .addComponent(panel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EnterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EnterMouseClicked
        try {
            // TODO add your handling code here:
            loginCheck();
        } catch (SQLException ex) {
            Logger.getLogger(loginForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FontFormatException ex) {
            Logger.getLogger(loginForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(loginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_EnterMouseClicked

    private void btn_EnterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EnterMouseEntered
        // TODO add your handling code here:
        btn_Enter.setForeground(new Color(14,155,0));
    }//GEN-LAST:event_btn_EnterMouseEntered

    private void btn_EnterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EnterMouseExited
        // TODO add your handling code here:
        btn_Enter.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_EnterMouseExited

    private void lbl_signUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_signUpMouseClicked
        // TODO add your handling code here:
        this.dispose();
        try {
            new registerForm().setVisible(true);
        } catch (FontFormatException ex) {
            Logger.getLogger(loginForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(loginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lbl_signUpMouseClicked

    private void loginCheck() throws SQLException, FontFormatException, IOException{
        String username;
        String password;
        if(txt_User.getText().isEmpty() || txt_Pass.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please type your username and password!");
        }else{
            db.conn = DriverManager.getConnection(db.DB_URL, db.USER, db.PASS);
            //Check if connected
            /*if (db.conn != null) {
            System.out.println("Connected");
            }else{
            System.out.println("Connection Error");
            }*/
            username = txt_User.getText();
            password = txt_Pass.getText();
            String sql = String.format("SELECT count(*) from LOGIN where user_id = '%s' AND user_pass = '%s'",username,password);
            
            //'PreparedStatement' - an object that represents a precompiled SQL statement
            PreparedStatement ps = db.conn.prepareStatement(sql);
            
            //'ResultSet' - a table of data representing a database result set
            ResultSet rs = ps.executeQuery();
            
            //rs.next() is a method of the ResultSet interface moves the pointer of the current (ResultSet) object to the next row
            rs.next(); //
            
            //Check result if more than 0
            int count = rs.getInt(1);
            
            if(count>0){
                // Add +1 to loginCount
                sql = String.format("SELECT logincount from LOGIN where user_id = '%s' AND user_pass = '%s'",username,password);
                ps = db.conn.prepareStatement(sql);
                rs = ps.executeQuery();
                rs.next();
                count = rs.getInt(1);
                db.stmt = db.conn.createStatement();
                sql = String.format("UPDATE LOGIN "
                        + "SET LOGINCOUNT = '%d'"
                        + "WHERE USER_ID = '%s'",count+1,username);
                db.stmt.executeUpdate(sql);
                sql = String.format("SELECT account_id from LOGIN where user_id = '%s'",username);
                ps = db.conn.prepareStatement(sql);
                rs = ps.executeQuery();
                rs.next();
                count = rs.getInt(1);
                sql = String.format("SELECT sum(total) "
                    + "FROM("
                        + "SELECT points as total, account_id "
                        + "FROM ENGLISH "
                        + "UNION ALL "
                        + "SELECT points, account_id "
                        + "FROM GEOGRAPHY "
                        + "UNION ALL "
                        + "SELECT points, account_id "
                        + "FROM MATH "
                        + "UNION ALL "
                        + "SELECT points, account_id "
                        + "FROM MUSICARTS "
                        + "UNION ALL "
                        + "SELECT points, account_id "
                        + "FROM SCIENCE "
                    + ") T "
                        + "WHERE T.account_id = '%d' "
                        + "GROUP BY T.account_id",count);
                ps = db.conn.prepareStatement(sql);
                rs = ps.executeQuery();
                rs.next();
                count = rs.getInt(1);
                sql = String.format("SELECT STATE FROM LOGIN WHERE user_id = '%s'",username);
                ps = db.conn.prepareStatement(sql);
                rs = ps.executeQuery();
                rs.next();
                int state = rs.getInt(1);
                this.dispose();
                dashboardForm dash = new dashboardForm();
                dash.setPoints(count);
                dash.setName(username);
                dash.isAdmin(state);
                dash.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Invalid account,please try again!");  
            }
            //Close the connection
            db.conn.close();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new loginForm().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(loginForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (FontFormatException ex) {
                    Logger.getLogger(loginForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Enter;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_signUp;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private java.awt.Panel panel5;
    private java.awt.Panel panel6;
    private javax.swing.JPasswordField txt_Pass;
    private javax.swing.JTextField txt_User;
    // End of variables declaration//GEN-END:variables
}
